#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh

runApplication decomposePar
runParallel $application

FOAM_LIBS="\(\"$FOAM_USER_LIBBIN/libautoDecomposingFileOperation.so\"\)" paraFoam


#------------------------------------------------------------------------------
