#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Allwmake error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

# Update OpenFOAM version strings if required
wmakePrintBuild -check || wrmo OpenFOAM/global/global.o 2>/dev/null

wmakeLnInclude OpenFOAM-dev.feature-globalFile
wmake $targetType OpenFOAM-dev.feature-globalFile
wmake

#------------------------------------------------------------------------------
