#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

[ -d 0 ] && \rm -r 0
cp -r 0.orig 0

##-- Run on single processor
#runApplication `getApplication`

#-- Run in parallel
runApplication decomposePar -allRegions
runParallel `getApplication`
runApplication reconstructPar -allRegions


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

#------------------------------------------------------------------------------
