#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication topoSet

runApplication removeFaces f0 -overwrite

runApplication -s 2 topoSet

runApplication subsetMesh -patch walls2 c1 -overwrite

runApplication icoFoam

#------------------------------------------------------------------------------
