#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication topoSet

runApplication refineHexMesh c0 -overwrite

runApplication -o topoSet

runApplication tetDecomposition pyramid -cellSet noHex -overwrite

runApplication foamToEnsight -ascii

#------------------------------------------------------------------------------
