#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. $WM_PROJECT_DIR/etc/config.sh/functions

_foamAddLib "${FOAM_USER_LIBBIN}/PstreamWithLocking/"

runApplication blockMesh

runApplication decomposePar

runParallel $(getApplication)

#------------------------------------------------------------------------------
