#!/bin/sh
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

#ln -s ../pimpleFoam_with_cyclicACMI/lnInclude .
wmake $targetType

#------------------------------------------------------------------------------
