#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

export FOAM_SIGFPE=false
runApplication flatten2DMesh '(movingWall)'
runApplication extrude2DMesh polyMesh2D

runApplication checkMesh

#------------------------------------------------------------------------------
