#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication subsetMesh -patch lift -overwrite c0
runApplication topoSet
cp -r 0.orig 0

#------------------------------------------------------------------------------
