#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Get some helper functions
. $WM_PROJECT_DIR/etc/config.sh/functions
. $WM_PROJECT_DIR/wmake/scripts/wmakeFunctions

#_foamAddPath "$me/applications/test/local_compilation/scripts/"
PATH="$me/applications/test/local_compilation/scripts:$PATH"

#------------------------------------------------------------------------------
