#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -s level0 blockMesh -region level0
runApplication -s level1 blockMesh -region level1

runApplication simpleFoam_MG

#------------------------------------------------------------------------------
