#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase -region level0
cleanCase -region level1
cleanCase -region level2
cleanCase

#------------------------------------------------------------------------------
