#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
(cd constant/staticDisplacement && rm polyMesh && ln -s ../polyMesh .)

runApplication moveDynamicMesh

#------------------------------------------------------------------------------
