#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

(cd MG/level1 && cleanCase)
(cd MG/level2 && cleanCase)
(cd MG/level3 && cleanCase)
(cd MG/level4 && cleanCase)
cleanCase

#------------------------------------------------------------------------------
