#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

(cd MG/level1 && runApplication blockMesh)
(cd MG/level2 && runApplication blockMesh)
(cd MG/level3 && runApplication blockMesh)
(cd MG/level4 && runApplication blockMesh)

runApplication MGsimpleFoam

#------------------------------------------------------------------------------
