#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

if [ ! -d "${ZFP_ROOT}" ]; then
    echo "Please set ZFP_ROOT to the root of the zfp installation"
    exit 1
fi

wmake

#------------------------------------------------------------------------------
