#!/bin/sh
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmakeLnInclude .
wmake $targetType

#------------------------------------------------------------------------------
